import { Exercise, ExerciseCategory, DifficultyLevel, MuscleGroup, EquipmentType } from '../../src/domains/fitness-planning/entities/exercise.entity';

export const exerciseSeeds: Partial<Exercise>[] = [
  // Bodyweight Exercises
  {
    name: 'Push-ups',
    description: 'Classic bodyweight exercise for upper body strength. Targets chest, shoulders, and triceps.',
    instructions: '1. Start in plank position with hands slightly wider than shoulders\n2. Lower body until chest nearly touches floor\n3. Push back up to starting position\n4. Keep core tight throughout movement',
    category: ExerciseCategory.CALISTHENICS,
    difficultyLevel: DifficultyLevel.BEGINNER,
    primaryMuscleGroup: MuscleGroup.CHEST,
    secondaryMuscleGroups: [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS, MuscleGroup.CORE],
    equipment: [EquipmentType.NONE],
    safetyNotes: 'Keep core engaged to protect lower back. Modify on knees if needed.',
    formCues: ['Hands under shoulders', 'Straight line from head to heels', 'Control the descent'],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 15,
    defaultRestSeconds: 60,
    caloriesPerMinute: 7,
    metValue: 8.0,
    tags: ['bodyweight', 'upper-body', 'compound'],
    workoutTypes: ['strength', 'calisthenics'],
    isCompound: true,
    isBodyweight: true,
    isActive: true,
    createdBy: 'system',
  },
  {
    name: 'Squats',
    description: 'Fundamental lower body exercise targeting quadriceps, glutes, and hamstrings.',
    instructions: '1. Stand with feet shoulder-width apart\n2. Lower hips back and down as if sitting in chair\n3. Keep chest up and weight on heels\n4. Return to standing position',
    category: ExerciseCategory.CALISTHENICS,
    difficultyLevel: DifficultyLevel.BEGINNER,
    primaryMuscleGroup: MuscleGroup.QUADRICEPS,
    secondaryMuscleGroups: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: [EquipmentType.NONE],
    healthConditionsToAvoid: ['knee injury', 'hip replacement'],
    safetyNotes: 'Keep knees in line with toes. Don\'t let knees cave inward.',
    formCues: ['Weight on heels', 'Chest up', 'Knees track over toes'],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 20,
    defaultRestSeconds: 60,
    caloriesPerMinute: 8,
    metValue: 5.0,
    tags: ['bodyweight', 'lower-body', 'compound'],
    workoutTypes: ['strength', 'functional'],
    isCompound: true,
    isBodyweight: true,
    isActive: true,
    createdBy: 'system',
  },
  {
    name: 'Plank',
    description: 'Isometric core strengthening exercise that also engages shoulders and glutes.',
    instructions: '1. Start in push-up position\n2. Lower to forearms\n3. Hold straight line from head to heels\n4. Breathe normally while holding position',
    category: ExerciseCategory.CORE,
    difficultyLevel: DifficultyLevel.BEGINNER,
    primaryMuscleGroup: MuscleGroup.CORE,
    secondaryMuscleGroups: [MuscleGroup.SHOULDERS, MuscleGroup.GLUTES],
    equipment: [EquipmentType.YOGA_MAT],
    safetyNotes: 'Don\'t let hips sag or pike up. Stop if you feel strain in lower back.',
    formCues: ['Straight line', 'Engaged core', 'Neutral neck'],
    defaultSets: 3,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 60,
    caloriesPerMinute: 4,
    metValue: 4.0,
    tags: ['bodyweight', 'core', 'isometric'],
    workoutTypes: ['core', 'stability'],
    isCompound: false,
    isBodyweight: true,
    isActive: true,
    createdBy: 'system',
  },
  {
    name: 'Mountain Climbers',
    description: 'Dynamic cardio exercise that combines core strength with cardiovascular conditioning.',
    instructions: '1. Start in plank position\n2. Bring right knee to chest\n3. Quickly switch legs\n4. Continue alternating at fast pace',
    category: ExerciseCategory.CARDIO,
    difficultyLevel: DifficultyLevel.INTERMEDIATE,
    primaryMuscleGroup: MuscleGroup.CORE,
    secondaryMuscleGroups: [MuscleGroup.SHOULDERS, MuscleGroup.QUADRICEPS],
    equipment: [EquipmentType.NONE],
    safetyNotes: 'Maintain plank position throughout. Start slowly and build up speed.',
    formCues: ['Keep hips level', 'Drive knees to chest', 'Quick feet'],
    defaultSets: 3,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 90,
    caloriesPerMinute: 12,
    metValue: 8.0,
    tags: ['bodyweight', 'cardio', 'core', 'high-intensity'],
    workoutTypes: ['cardio', 'hiit'],
    isCompound: true,
    isBodyweight: true,
    isCardio: true,
    isActive: true,
    createdBy: 'system',
  },

  // Resistance Band Exercises
  {
    name: 'Resistance Band Rows',
    description: 'Upper back strengthening exercise using resistance bands. Great for posture improvement.',
    instructions: '1. Secure band at chest height\n2. Hold handles with arms extended\n3. Pull handles to sides of torso\n4. Squeeze shoulder blades together\n5. Slowly return to start',
    category: ExerciseCategory.RESISTANCE,
    difficultyLevel: DifficultyLevel.BEGINNER,
    primaryMuscleGroup: MuscleGroup.BACK,
    secondaryMuscleGroups: [MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
    equipment: [EquipmentType.RESISTANCE_BANDS],
    safetyNotes: 'Check band for wear before use. Keep core engaged throughout movement.',
    formCues: ['Pull with back muscles', 'Squeeze shoulder blades', 'Control the return'],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 18,
    defaultRestSeconds: 60,
    caloriesPerMinute: 6,
    metValue: 4.5,
    tags: ['resistance-band', 'upper-body', 'posture'],
    workoutTypes: ['strength', 'rehabilitation'],
    isCompound: true,
    isActive: true,
    createdBy: 'system',
  },

  // Dumbbell Exercises
  {
    name: 'Dumbbell Squats',
    description: 'Weighted squat variation using dumbbells to increase resistance and challenge.',
    instructions: '1. Hold dumbbells at shoulders or sides\n2. Stand with feet shoulder-width apart\n3. Lower into squat position\n4. Drive through heels to return to standing',
    category: ExerciseCategory.RESISTANCE,
    difficultyLevel: DifficultyLevel.INTERMEDIATE,
    primaryMuscleGroup: MuscleGroup.QUADRICEPS,
    secondaryMuscleGroups: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: [EquipmentType.DUMBBELLS],
    healthConditionsToAvoid: ['knee injury', 'back injury'],
    safetyNotes: 'Start with light weight to master form. Keep dumbbells close to body.',
    formCues: ['Chest up', 'Weight on heels', 'Control the weight'],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    caloriesPerMinute: 10,
    metValue: 6.0,
    tags: ['dumbbell', 'lower-body', 'compound'],
    workoutTypes: ['strength', 'muscle-building'],
    isCompound: true,
    isActive: true,
    createdBy: 'system',
  },

  // Yoga/Flexibility
  {
    name: 'Cat-Cow Stretch',
    description: 'Gentle spinal mobility exercise that helps reduce back tension and improve flexibility.',
    instructions: '1. Start on hands and knees\n2. Arch back and look up (Cow)\n3. Round spine and tuck chin (Cat)\n4. Flow smoothly between positions',
    category: ExerciseCategory.YOGA,
    difficultyLevel: DifficultyLevel.BEGINNER,
    primaryMuscleGroup: MuscleGroup.BACK,
    secondaryMuscleGroups: [MuscleGroup.CORE],
    equipment: [EquipmentType.YOGA_MAT],
    safetyNotes: 'Move slowly and gently. Stop if you feel any sharp pain.',
    formCues: ['Smooth movement', 'Breathe with movement', 'Feel the stretch'],
    defaultSets: 2,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 30,
    caloriesPerMinute: 2,
    metValue: 2.5,
    tags: ['yoga', 'flexibility', 'mobility', 'back-health'],
    workoutTypes: ['flexibility', 'mobility', 'warm-up', 'cool-down'],
    isCompound: false,
    isBodyweight: true,
    isActive: true,
    createdBy: 'system',
  },

  // Core Exercises
  {
    name: 'Dead Bug',
    description: 'Core stability exercise that teaches proper core engagement while moving limbs.',
    instructions: '1. Lie on back with arms up and knees bent 90°\n2. Lower opposite arm and leg slowly\n3. Return to start position\n4. Repeat on other side',
    category: ExerciseCategory.CORE,
    difficultyLevel: DifficultyLevel.BEGINNER,
    primaryMuscleGroup: MuscleGroup.CORE,
    equipment: [EquipmentType.YOGA_MAT],
    safetyNotes: 'Keep lower back pressed to floor. Move slowly and controlled.',
    formCues: ['Back flat on floor', 'Slow movement', 'Opposite arm and leg'],
    defaultSets: 3,
    defaultRepsMin: 6,
    defaultRepsMax: 10,
    defaultRestSeconds: 45,
    caloriesPerMinute: 3,
    metValue: 3.0,
    tags: ['bodyweight', 'core', 'stability', 'rehabilitation'],
    workoutTypes: ['core', 'stability', 'rehabilitation'],
    isCompound: false,
    isBodyweight: true,
    isActive: true,
    createdBy: 'system',
  },

  // Cardio Exercises
  {
    name: 'Jumping Jacks',
    description: 'Classic cardio exercise that elevates heart rate and improves coordination.',
    instructions: '1. Start with feet together, arms at sides\n2. Jump feet apart while raising arms overhead\n3. Jump back to starting position\n4. Maintain steady rhythm',
    category: ExerciseCategory.CARDIO,
    difficultyLevel: DifficultyLevel.BEGINNER,
    primaryMuscleGroup: MuscleGroup.CARDIO,
    secondaryMuscleGroups: [MuscleGroup.SHOULDERS, MuscleGroup.CALVES],
    equipment: [EquipmentType.NONE],
    healthConditionsToAvoid: ['joint problems', 'recent surgery'],
    safetyNotes: 'Land softly on balls of feet. Modify by stepping instead of jumping.',
    formCues: ['Soft landings', 'Steady rhythm', 'Full range of motion'],
    defaultSets: 3,
    defaultDurationSeconds: 45,
    defaultRestSeconds: 60,
    caloriesPerMinute: 10,
    metValue: 7.0,
    tags: ['bodyweight', 'cardio', 'coordination'],
    workoutTypes: ['cardio', 'warm-up'],
    isCompound: true,
    isBodyweight: true,
    isCardio: true,
    isActive: true,
    createdBy: 'system',
  },

  // Advanced Exercises
  {
    name: 'Burpees',
    description: 'Full-body exercise combining squat, plank, push-up, and jump for ultimate conditioning.',
    instructions: '1. Start standing\n2. Squat down and place hands on floor\n3. Jump feet back to plank\n4. Do push-up (optional)\n5. Jump feet back to squat\n6. Jump up with arms overhead',
    category: ExerciseCategory.CALISTHENICS,
    difficultyLevel: DifficultyLevel.ADVANCED,
    primaryMuscleGroup: MuscleGroup.FULL_BODY,
    equipment: [EquipmentType.NONE],
    healthConditionsToAvoid: ['heart conditions', 'joint problems', 'back injury'],
    safetyNotes: 'High-intensity exercise. Start slowly and build endurance. Stop if dizzy.',
    formCues: ['Smooth transitions', 'Controlled landing', 'Breathe rhythmically'],
    defaultSets: 3,
    defaultRepsMin: 5,
    defaultRepsMax: 10,
    defaultRestSeconds: 120,
    caloriesPerMinute: 15,
    metValue: 10.0,
    tags: ['bodyweight', 'full-body', 'high-intensity', 'conditioning'],
    workoutTypes: ['hiit', 'conditioning', 'strength'],
    isCompound: true,
    isBodyweight: true,
    isCardio: true,
    isActive: true,
    createdBy: 'system',
  },
];